In [40]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import column_generation
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
df = pd.read_csv("datasets/wdbc.data", header=None)

In [15]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [43]:
X = df.values[:,2:]
y = (df[1]=='M').apply(lambda x: -1 if x else 1).values.astype(float)

In [41]:
np.unique(y)

array([-1,  1], dtype=int64)

In [68]:
column_generation.column_generation(X, y, C=1)

-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Mar 25 12:07:42 AM: Problem status: optimal
(CVXPY) Mar 25 12:07:42 AM: Optimal value: 7.771e+01
(CVXPY) Mar 25 12:07:42 AM: Compilation took 4.739e-02 seconds
(CVXPY) Mar 25 12:07:42 AM: Solver (including time spent in interface) took 5.745e-02 seconds
                                     CVXPY                                     
                                     v1.3.1                                    
(CVXPY) Mar 25 12:07:46 AM: Your problem has 569 variables, 65 constraints, and 0 parameters.
(CVXPY) Mar 25 12:07:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 25 12:07:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 25 12:07:46 AM: C

array([ 9.81811481e-10,  9.99999995e-01,  1.92651364e-11,  4.55763953e-02,
        6.97050901e-02,  2.78379404e-10, -1.71579663e-11,  3.13883192e-12,
        9.99999999e-01,  2.26818152e-10,  1.00000000e+00,  1.50464926e-10,
        1.60351217e-10,  2.84773141e-10,  5.46916899e-01,  1.79027766e-12,
       -3.29233378e-11,  6.23253174e-12,  1.27304602e-11,  1.00000000e+00,
       -6.06755189e-11, -5.43255998e-11,  9.81811481e-10, -2.05168572e-11,
       -6.27379540e-12,  9.81811481e-10,  2.51396694e-01,  2.68762748e-11,
        1.24809082e-11,  1.00000000e+00,  2.61786958e-11,  3.90619361e-11,
        1.55427163e-11,  6.80731163e-12,  1.13926133e-10,  3.38600816e-11,
        8.82708651e-11, -6.28234029e-11,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.44406044e-10,  1.75068252e-11,
        6.57981620e-11,  1.43973148e-09, -5.39401178e-11,  9.99999999e-01,
        3.16973870e-11,  1.00000000e+00,  1.52219399e-11, -6.41113222e-11,
       -6.01515807e-11,  

                                     CVXPY                                     
                                     v1.3.1                                    
(CVXPY) Mar 25 12:07:56 AM: Your problem has 569 variables, 63 constraints, and 0 parameters.
(CVXPY) Mar 25 12:07:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 25 12:07:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 25 12:07:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Mar 25 12:07:56 AM: Compiling problem (target solver=ECOS).
(CVXPY) Mar 25 12:07:56 AM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> Co

array([ 9.81811481e-10,  9.99999995e-01,  1.92651364e-11,  4.55763953e-02,
        6.97050901e-02,  2.78379404e-10, -1.71579663e-11,  3.13883192e-12,
        9.99999999e-01,  2.26818152e-10,  1.00000000e+00,  1.50464926e-10,
        1.60351217e-10,  2.84773141e-10,  5.46916899e-01,  1.79027766e-12,
       -3.29233378e-11,  6.23253174e-12,  1.27304602e-11,  1.00000000e+00,
       -6.06755189e-11, -5.43255998e-11,  9.81811481e-10, -2.05168572e-11,
       -6.27379540e-12,  9.81811481e-10,  2.51396694e-01,  2.68762748e-11,
        1.24809082e-11,  1.00000000e+00,  2.61786958e-11,  3.90619361e-11,
        1.55427163e-11,  6.80731163e-12,  1.13926133e-10,  3.38600816e-11,
        8.82708651e-11, -6.28234029e-11,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.44406044e-10,  1.75068252e-11,
        6.57981620e-11,  1.43973148e-09, -5.39401178e-11,  9.99999999e-01,
        3.16973870e-11,  1.00000000e+00,  1.52219399e-11, -6.41113222e-11,
       -6.01515807e-11,  