In [117]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import column_generation
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
df = pd.read_csv("datasets/wdbc.data", header=None)

In [15]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [158]:
X = df.values[:,2:]
y = (df[1]=='M').apply(lambda x: -1 if x else 1).values.astype(float)

In [159]:
X = Normalizer().fit_transform(X)

In [183]:
np.unique(y)

array([-1.,  1.])

In [171]:
lambda_star, F, soglie = column_generation.column_generation(X, y, C=1)

iteration 0----------------------------------------------------------------------------------------------------
                                     CVXPY                                     
                                     v1.3.1                                    
(CVXPY) Mar 25 12:27:58 PM: Your problem has 569 variables, 63 constraints, and 0 parameters.
(CVXPY) Mar 25 12:27:58 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 25 12:27:58 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 25 12:27:58 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Mar 25 12:27:58 PM: Compiling problem (tar

In [172]:
len(soglie)

107

In [184]:
soglie

[0.015061278825455734,
 0.02035203707696362,
 0.09715082124237309,
 0.6152191536736598,
 0.00010382548434629268,
 9.400124144489939e-05,
 6.385504500725327e-05,
 3.848156566475069e-05,
 0.0001935251157761468,
 6.885551280820014e-05,
 0.0003431004585810102,
 0.001129722453085095,
 0.0024201895900099776,
 0.03016316620591424,
 6.714754547302155e-06,
 1.990805887666662e-05,
 2.3068057804551835e-05,
 1.0401045022016667e-05,
 2.0344242108964787e-05,
 3.112070332515592e-06,
 0.016722037936136875,
 0.02702670111436188,
 0.10976032039475694,
 0.7689139117556564,
 0.0001416437816229937,
 0.0002216099885150834,
 0.00021252175334302874,
 0.0001019585470928296,
 0.0003075750854497092,
 8.922689327513233e-05,
 [0.014322813074828378, 0.00866575594824031],
 [0.017923366819729537, 0.007486168361702981],
 [0.09686907634576881, 0.05598828223243254],
 [5.377000369526866e-05, 3.3129559930462714e-05],
 [3.1683519200890175e-05, 1.6256720656877108e-05],
 [2.602650887954765e-05, 2.5125832622811214e-05],
 [0.0

In [ ]:
for phi in F:


In [173]:
lambda_star

array([-6.79441668e-09, -1.29765817e-09, -3.77035199e-09,  2.84673782e-01,
        2.26145748e-09,  1.43598734e-07, -1.89672093e-10,  5.95084706e-09,
        6.05145946e-09,  7.77799237e-08,  3.87066587e-09, -2.82985554e-09,
        9.48300774e-01,  6.39040649e-01,  4.52724305e-01, -3.76861463e-09,
        2.24854816e-08,  9.01205033e-09, -1.50788203e-09,  9.99999994e-01,
       -7.91268703e-09, -3.97027294e-09,  2.39932065e-08,  1.67147763e-08,
       -2.73760436e-09,  2.40204690e-10,  6.32647944e-08, -3.13514153e-09,
       -3.68886693e-10,  1.38160486e-01, -6.49856684e-09,  6.74539217e-01,
       -6.73153671e-09,  3.47456938e-10, -1.12413956e-09, -5.74115939e-09,
        7.38960667e-01, -5.80244280e-09,  9.99999938e-01, -2.06227395e-09,
        7.43657628e-01,  6.79438244e-01, -6.82455216e-09,  4.37944908e-08,
        6.63044201e-02, -6.77837182e-09, -6.86149230e-09,  1.05458553e-08,
       -5.04959270e-09,  2.19239509e-08, -2.52358258e-09, -2.88650459e-09,
       -4.83396298e-09, -

In [174]:
lambda_star = np.array([0 if l < 1e-6 else l for l in lambda_star])

In [175]:
lambda_star

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.84673782e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       9.48300774e-01, 6.39040649e-01, 4.52724305e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.99999994e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.38160486e-01, 0.00000000e+00, 6.74539217e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       7.38960667e-01, 0.00000000e+00, 9.99999938e-01, 0.00000000e+00,
       7.43657628e-01, 6.79438244e-01, 0.00000000e+00, 0.00000000e+00,
       6.63044201e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.18736363e-01, 0.00000000e+00,
      

In [176]:
def compute_out(x):

    def score(i):
        score = 0
        for phi in F:
            score =+ lambda_star[i] * phi[i] * (x @ X[i])
        return score

    out = np.sum(np.array(list(map(score, np.arange(len(lambda_star)))))) #+ self.b
    # print(out)
    return out

def parallel_predict(x):
    return np.array(list(map(compute_out, x)))

def predict(x):
    out = parallel_predict(x)
    return np.sign(out)


In [179]:
y_pred = predict(X)

In [180]:
np.unique(y_pred)

array([1.])

In [182]:
accuracy_score(y, y_pred)

0.6274165202108963